### ISSUE TITLE
How to stop observing?

### ISSUE THREAD

**Issue by sp00x** [aheckmann/observed#18]
The documentation doesn't really describe how to _stop_ listening for events?

It being an EventEmitter you can obviously do ```ee.removeAllListeners()``` but I assume that will leak memory. I notice there is an ```ee.stop()``` method also, which seems to do what I'm looking for, but I'm not 100% sure (and I would not want to stop other instances observing a specific object, only the one I'm trying to sto)

Maybe the documentation should include some information on this?

**Comment by aheckmann** [comment]
yeah, didn't document `stop()` yet. good catch.
